export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: string
  dietary: "veg" | "non-veg" | "vegan"
  spice?: "mild" | "medium" | "bold"
  portion: "light" | "regular" | "shareable"
  pairing: string
  chefNote?: string
  isPopular?: boolean
  available?: boolean
}

export const menuCategories = [
  { id: "pizzas", name: "Pizzas", description: "Wood-fired pizzas with Indian flavors" },
  { id: "burgers", name: "Burgers", description: "Gourmet burgers with premium toppings" },
  { id: "sandwiches", name: "Sandwiches & Wraps", description: "Quick bites and wraps" },
  { id: "appetizers", name: "Appetizers", description: "Starters and fried snacks" },
  { id: "beverages", name: "Beverages", description: "Cold drinks and hot beverages" },
  { id: "desserts", name: "Desserts", description: "Sweet treats and pastries" },
  { id: "combos", name: "Combo Meals", description: "Best value meal deals" },
  { id: "specials", name: "Chef Specials", description: "House favorites" },
]

export const menuItems: MenuItem[] = [
  // Pizzas (6 items)
  {
    id: "p1",
    name: "Paneer Tikka Pizza",
    description: "Marinated paneer, onions, capsicum, tandoori sauce",
    price: 249,
    image: "/paneer-tikka-pizza.jpg",
    category: "pizzas",
    dietary: "veg",
    spice: "medium",
    portion: "regular",
    pairing: "Mango Lassi",
    isPopular: true,
  },
  {
    id: "p2",
    name: "Tandoori Chicken Pizza",
    description: "Tandoori chicken, onions, cilantro, mint sauce",
    price: 299,
    image: "/tandoori-chicken-pizza.jpg",
    category: "pizzas",
    dietary: "non-veg",
    spice: "medium",
    portion: "regular",
    pairing: "Iced Tea",
    isPopular: true,
  },
  {
    id: "p3",
    name: "Margherita Pizza",
    description: "Fresh mozzarella, basil, tomato sauce, olive oil",
    price: 199,
    image: "/margherita-pizza.png",
    category: "pizzas",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Sprite",
  },
  {
    id: "p4",
    name: "Spicy Pepperoni Pizza",
    description: "Double pepperoni, mozzarella, chili oil",
    price: 279,
    image: "/pepperoni-pizza.jpg",
    category: "pizzas",
    dietary: "non-veg",
    spice: "bold",
    portion: "regular",
    pairing: "Cola",
  },
  {
    id: "p5",
    name: "Veggie Supreme Pizza",
    description: "Bell peppers, mushrooms, onions, olives, corn, spinach",
    price: 229,
    image: "/veggie-pizza.jpg",
    category: "pizzas",
    dietary: "vegan",
    spice: "mild",
    portion: "regular",
    pairing: "Orange Juice",
  },
  {
    id: "p6",
    name: "Meat Feast Pizza",
    description: "Pepperoni, sausage, bacon, ham, mozzarella",
    price: 329,
    image: "/meat-pizza.jpg",
    category: "pizzas",
    dietary: "non-veg",
    spice: "medium",
    portion: "shareable",
    pairing: "Craft Soda",
  },

  // Burgers (7 items)
  {
    id: "b1",
    name: "Classic Cheeseburger",
    description: "Beef patty, cheddar cheese, lettuce, tomato, house sauce",
    price: 189,
    image: "/classic-cheeseburger.png",
    category: "burgers",
    dietary: "non-veg",
    spice: "mild",
    portion: "regular",
    pairing: "Fries & Cola",
  },
  {
    id: "b2",
    name: "Paneer Burger",
    description: "Grilled paneer, avocado, lettuce, tomato, mayo",
    price: 179,
    image: "/paneer-burger.jpg",
    category: "burgers",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Mango Lassi",
  },
  {
    id: "b3",
    name: "Tandoori Chicken Burger",
    description: "Tandoori chicken, cucumber raita, mint chutney, onions",
    price: 219,
    image: "/tandoori-burger.jpg",
    category: "burgers",
    dietary: "non-veg",
    spice: "medium",
    portion: "regular",
    pairing: "Lemon Iced Tea",
  },
  {
    id: "b4",
    name: "Spicy Jalapeño Burger",
    description: "Beef patty, jalapeños, pepper jack cheese, sriracha mayo",
    price: 209,
    image: "/jalapeno-burger.jpg",
    category: "burgers",
    dietary: "non-veg",
    spice: "bold",
    portion: "regular",
    pairing: "Horchata",
  },
  {
    id: "b5",
    name: "Double Bacon Burger",
    description: "Two beef patties, crispy bacon, Swiss cheese, caramelized onions",
    price: 249,
    image: "/bacon-burger.jpg",
    category: "burgers",
    dietary: "non-veg",
    spice: "medium",
    portion: "regular",
    pairing: "Milkshake",
  },
  {
    id: "b6",
    name: "Mushroom Swiss Burger",
    description: "Beef patty, sautéed mushrooms, Swiss cheese, garlic aioli",
    price: 199,
    image: "/mushroom-burger.jpg",
    category: "burgers",
    dietary: "non-veg",
    spice: "mild",
    portion: "regular",
    pairing: "Iced Coffee",
  },
  {
    id: "b7",
    name: "Vegan Burger",
    description: "Plant-based patty, avocado, lettuce, tomato, vegan mayo",
    price: 169,
    image: "/vegan-burger.jpg",
    category: "burgers",
    dietary: "vegan",
    spice: "mild",
    portion: "regular",
    pairing: "Green Tea",
  },

  // Sandwiches & Wraps (6 items)
  {
    id: "s1",
    name: "Chicken Tikka Wrap",
    description: "Marinated chicken, onions, capsicum, mint chutney in whole wheat wrap",
    price: 149,
    image: "/chicken-wrap.jpg",
    category: "sandwiches",
    dietary: "non-veg",
    spice: "medium",
    portion: "regular",
    pairing: "Iced Tea",
  },
  {
    id: "s2",
    name: "Paneer & Veggie Sandwich",
    description: "Grilled paneer, bell peppers, cucumber, green chutney",
    price: 129,
    image: "/paneer-sandwich.jpg",
    category: "sandwiches",
    dietary: "veg",
    spice: "mild",
    portion: "light",
    pairing: "Lemonade",
  },
  {
    id: "s3",
    name: "Tandoori Lamb Wrap",
    description: "Tender lamb, yogurt, mint, tamarind chutney",
    price: 189,
    image: "/lamb-wrap.jpg",
    category: "sandwiches",
    dietary: "non-veg",
    spice: "medium",
    portion: "regular",
    pairing: "Buttermilk",
  },
  {
    id: "s4",
    name: "Veggie Delight Wrap",
    description: "Mixed vegetables, sprouts, cucumber, hummus",
    price: 119,
    image: "/veggie-wrap.jpg",
    category: "sandwiches",
    dietary: "vegan",
    spice: "mild",
    portion: "light",
    pairing: "Fresh Juice",
  },
  {
    id: "s5",
    name: "Egg & Cheese Toastie",
    description: "Scrambled eggs, melted cheese, toast",
    price: 99,
    image: "/egg-toastie.jpg",
    category: "sandwiches",
    dietary: "veg",
    spice: "mild",
    portion: "light",
    pairing: "Tea",
  },
  {
    id: "s6",
    name: "Crispy Chicken Sandwich",
    description: "Fried chicken, coleslaw, spicy mayo",
    price: 139,
    image: "/chicken-sandwich.jpg",
    category: "sandwiches",
    dietary: "non-veg",
    spice: "medium",
    portion: "regular",
    pairing: "Cola",
  },

  // Appetizers (7 items)
  {
    id: "a1",
    name: "Paneer Tikka (6pc)",
    description: "Marinated cottage cheese skewers, grilled",
    price: 169,
    image: "/paneer-tikka.png",
    category: "appetizers",
    dietary: "veg",
    spice: "medium",
    portion: "light",
    pairing: "Mint Chutney",
  },
  {
    id: "a2",
    name: "Chicken Wings (6pc)",
    description: "Spicy buffalo or BBQ glazed crispy wings",
    price: 179,
    image: "/chicken-wings.jpg",
    category: "appetizers",
    dietary: "non-veg",
    spice: "bold",
    portion: "light",
    pairing: "Ranch Dip",
  },
  {
    id: "a3",
    name: "Onion Rings",
    description: "Crispy battered onion rings with spiced salt",
    price: 99,
    image: "/onion-rings.jpg",
    category: "appetizers",
    dietary: "veg",
    spice: "medium",
    portion: "regular",
    pairing: "Ketchup",
  },
  {
    id: "a4",
    name: "Samosa (4pc)",
    description: "Crispy potato and pea samosa with tamarind chutney",
    price: 89,
    image: "/crispy-golden-samosas.png",
    category: "appetizers",
    dietary: "veg",
    spice: "medium",
    portion: "light",
    pairing: "Green Chutney",
  },
  {
    id: "a5",
    name: "Chicken Tenders (4pc)",
    description: "Breaded and fried chicken tenders with sauce",
    price: 149,
    image: "/chicken-tenders.jpg",
    category: "appetizers",
    dietary: "non-veg",
    spice: "mild",
    portion: "light",
    pairing: "Honey Mustard",
  },
  {
    id: "a6",
    name: "Loaded Nachos",
    description: "Crispy chips with cheese, jalapeños, sour cream, salsa",
    price: 129,
    image: "/plate-of-loaded-nachos.png",
    category: "appetizers",
    dietary: "veg",
    spice: "medium",
    portion: "regular",
    pairing: "Guacamole",
  },
  {
    id: "a7",
    name: "Pakora Mix (8pc)",
    description: "Mixed vegetable and paneer pakora, served hot",
    price: 109,
    image: "/pakora.jpg",
    category: "appetizers",
    dietary: "veg",
    spice: "medium",
    portion: "light",
    pairing: "Tamarind Chutney",
  },

  // Beverages (6 items)
  {
    id: "bev1",
    name: "Iced Latte",
    description: "Cold espresso with smooth milk and ice",
    price: 99,
    image: "/iced-latte.jpg",
    category: "beverages",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Pastry",
  },
  {
    id: "bev2",
    name: "Mango Lassi",
    description: "Fresh mango blended with yogurt and honey",
    price: 129,
    image: "/mango-lassi.jpg",
    category: "beverages",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Samosa",
  },
  {
    id: "bev3",
    name: "Caramel Macchiato",
    description: "Espresso with steamed milk and caramel drizzle",
    price: 119,
    image: "/caramel-macchiato.jpg",
    category: "beverages",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Cake",
  },
  {
    id: "bev4",
    name: "Fresh Lemonade",
    description: "Fresh lemon juice, sugar, purified water",
    price: 79,
    image: "/refreshing-lemonade.png",
    category: "beverages",
    dietary: "vegan",
    spice: "mild",
    portion: "regular",
    pairing: "Fries",
  },
  {
    id: "bev5",
    name: "Strawberry Milkshake",
    description: "Blended strawberries with vanilla ice cream and milk",
    price: 129,
    image: "/classic-milkshake.png",
    category: "beverages",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Burger",
  },
  {
    id: "bev6",
    name: "Iced Chai Latte",
    description: "Cold spiced tea with milk and ice",
    price: 99,
    image: "/chai-latte.jpg",
    category: "beverages",
    dietary: "veg",
    spice: "medium",
    portion: "regular",
    pairing: "Samosa",
  },

  // Desserts (6 items)
  {
    id: "d1",
    name: "Chocolate Chip Cookie",
    description: "Warm cookie loaded with dark chocolate chips",
    price: 79,
    image: "/chocolate-chip-cookie.png",
    category: "desserts",
    dietary: "veg",
    spice: "mild",
    portion: "light",
    pairing: "Coffee",
  },
  {
    id: "d2",
    name: "Gulab Jamun (4pc)",
    description: "Sweet milk solids in sugar syrup, served warm",
    price: 89,
    image: "/gulab-jamun.png",
    category: "desserts",
    dietary: "veg",
    spice: "mild",
    portion: "light",
    pairing: "Chai",
  },
  {
    id: "d3",
    name: "Chocolate Brownie",
    description: "Fudgy chocolate brownie with whipped cream",
    price: 119,
    image: "/chocolate-brownie.png",
    category: "desserts",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Espresso",
  },
  {
    id: "d4",
    name: "Vanilla Ice Cream Cup",
    description: "Creamy vanilla ice cream with waffle cone",
    price: 99,
    image: "/ice-cream.jpg",
    category: "desserts",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Iced Coffee",
  },
  {
    id: "d5",
    name: "Cheesecake Slice",
    description: "New York style cheesecake with berry topping",
    price: 129,
    image: "/classic-cheesecake.png",
    category: "desserts",
    dietary: "veg",
    spice: "mild",
    portion: "light",
    pairing: "Tea",
  },
  {
    id: "d6",
    name: "Kheer Cup",
    description: "Traditional rice pudding with nuts and raisins",
    price: 99,
    image: "/creamy-kheer.png",
    category: "desserts",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Chai",
  },

  // Combo Meals (5 items)
  {
    id: "c1",
    name: "Burger Combo",
    description: "Burger + Fries + Drink (Medium)",
    price: 349,
    image: "/burger-combo.jpg",
    category: "combos",
    dietary: "non-veg",
    spice: "mild",
    portion: "regular",
    pairing: "Best Value",
    chefNote: "Save ₹50",
  },
  {
    id: "c2",
    name: "Pizza Combo",
    description: "Pizza (Medium) + Drinks (2) + Garlic Bread",
    price: 449,
    image: "/pizza-combo.jpg",
    category: "combos",
    dietary: "veg",
    spice: "mild",
    portion: "shareable",
    pairing: "Family Deal",
    chefNote: "Save ₹70",
  },
  {
    id: "c3",
    name: "Breakfast Combo",
    description: "Egg Sandwich + Hash Browns + Tea/Coffee",
    price: 199,
    image: "/breakfast-combo.jpg",
    category: "combos",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Morning Special",
    chefNote: "Till 11 AM",
  },
  {
    id: "c4",
    name: "Wrap Combo",
    description: "Wrap + Fries + Drink (Medium)",
    price: 299,
    image: "/wrap-combo.jpg",
    category: "combos",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Quick Bite",
    chefNote: "Save ₹40",
  },
  {
    id: "c5",
    name: "Appetizer Combo",
    description: "Wings + Samosa + Onion Rings + Drink",
    price: 399,
    image: "/appetizer-combo.jpg",
    category: "combos",
    dietary: "non-veg",
    spice: "medium",
    portion: "shareable",
    pairing: "Party Pack",
    chefNote: "Save ₹80",
  },

  // Chef Specials (7 items)
  {
    id: "sp1",
    name: "Crispy Fries",
    description: "Golden fried potato fries with sea salt and chaat masala",
    price: 79,
    image: "/golden-crispy-fries.png",
    category: "specials",
    dietary: "vegan",
    spice: "medium",
    portion: "regular",
    pairing: "Burger or Wrap",
  },
  {
    id: "sp2",
    name: "Garlic Bread",
    description: "Toasted bread with garlic butter and herbs",
    price: 99,
    image: "/garlic-bread.png",
    category: "specials",
    dietary: "veg",
    spice: "mild",
    portion: "light",
    pairing: "Pizza",
  },
  {
    id: "sp3",
    name: "Loaded Fries",
    description: "Fries topped with cheese, bacon, jalapeños, sour cream",
    price: 149,
    image: "/loaded-fries.jpg",
    category: "specials",
    dietary: "non-veg",
    spice: "medium",
    portion: "regular",
    pairing: "Burger",
  },
  {
    id: "sp4",
    name: "Garden Salad",
    description: "Mixed greens, tomatoes, cucumbers, house dressing",
    price: 129,
    image: "/vibrant-mixed-salad.png",
    category: "specials",
    dietary: "vegan",
    spice: "mild",
    portion: "regular",
    pairing: "Wrap",
  },
  {
    id: "sp5",
    name: "Mac & Cheese",
    description: "Creamy pasta with cheddar cheese and herbs",
    price: 139,
    image: "/mac-cheese.jpg",
    category: "specials",
    dietary: "veg",
    spice: "mild",
    portion: "regular",
    pairing: "Drink",
  },
  {
    id: "sp6",
    name: "Honey Butter Chicken",
    description: "Tender chicken pieces glazed in honey-butter sauce",
    price: 189,
    image: "/honey-chicken.jpg",
    category: "specials",
    dietary: "non-veg",
    spice: "medium",
    portion: "regular",
    pairing: "Rice & Drink",
  },
  {
    id: "sp7",
    name: "Mixed Grill Platter",
    description: "Assorted grilled items: paneer, chicken, vegetables",
    price: 299,
    image: "/grill-platter.jpg",
    category: "specials",
    dietary: "non-veg",
    spice: "medium",
    portion: "shareable",
    pairing: "Naan & Drink",
  },
]
